### ISSUE TITLE
Add google-api-python-client as a requirement in the PyPI

### ISSUE THREAD

**Issue by martinmCGG** [NickHilton/googledrivecloner#4]
The .whl package ([v1.0.2](https://files.pythonhosted.org/packages/57/13/0f5464b66cc6a4994d45ba2a71ac6ff382ce2de1087de468100ee16d5db1/googledrive_cloner-1.0.2.tar.gz)) in PyPI seems to miss one of the [requirements](https://github.com/NickHilton/googledrivecloner/blob/main/requirements.txt) - there is only this: `Requires-Dist: google-auth-oauthlib (<0.5,>=0.4.3)`, not the `google-api-python-client`.

I suspect the issue's origin is here: https://github.com/NickHilton/googledrivecloner/blob/main/setup.py#L26 - assuming the list of requirements in `setup.py` should match the `requirements.txt`.

Workaround: install the `google-api-python-client` package manually. After that, everything works as expected.

Details: tested on Python3.7 (Debian 10, using `python3.7-venv`), I was getting `ModuleNotFoundError: No module named 'googleapiclient'`.
The `bin/pip3 install googledrive_cloner` command (inside the virtual environment) installed just the following packages: cachetools-5.0.0 certifi-2021.10.8 charset-normalizer-2.0.12 google-auth-2.6.2 google-auth-oauthlib-0.4.6 googledrive-cloner-1.0.2 idna-3.3 oauthlib-3.2.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.8 six-1.16.0 urllib3-1.26.9.

**Comment by NickHilton** [comment]
Fixed this now - Wondering if the requirement `"google-api-python-client>=2.0.2,<2.1"` is too strict though - could relax the requirement on the upper end (although haven't tested for breaking changes)
